events = [
  {
    "content" : "events/afro_comic_con.html",
    "output" : "docs/afro_comic_con.html",
    "EVENT_IMAGE" : "/static/images/events/acc_logo.jpg",
    "EVENT_TITLE" : "Afro Comic Con",
    "EVENT_DATES" : "Nov 3-7 2019",
    "EVENT_SPACE_NAME" : "SAE Expression College",
    "EVENT_SPACE_ADDRESS" : "6601 Shellmound St, Emeryville, CA 94608",
    "EVENT_ORGANIZER" : "The Afro Comic Con Planning Committe",
    "EVENT_ORGANIZER_URL": "https://www.afrocomiccon.org/",
    "EVENT_EMAIL" : "acc-planning@gmail.com",
    "EVENT_MODAL_ID" :"afro_comic_con",
  },
  {
    "content" : "events/travel_more5.html",
    "output" : "docs/travel_more5.html",
    "EVENT_IMAGE" : "/static/images/events/trvl_black_flyer.png",
    "EVENT_TITLE" : "Travel More Spend Less #5",
    "EVENT_DATES" : "August 25, 2019",
    "EVENT_SPACE_NAME" : "Kingston 11 Cuisine",
    "EVENT_SPACE_ADDRESS" : "2270 Telegraph Ave, Oakland, CA 94612",
    "EVENT_ORGANIZER" : "Traveling Black",
    "EVENT_ORGANIZER_URL": "https://traveling.black/",
    "EVENT_EMAIL" : "travelingblack@gmail.com",
    "EVENT_MODAL_ID" : "travel_more5",
  },
  {
    "content" : "events/black_to_yoga.html",
    "output" : "docs/black_to_yoga.html",
    "EVENT_IMAGE" : "/static/images/events/black_to_yoga_flyer.jpg",
    "EVENT_TITLE" : "Yoga Informational Workshop and Practice for Men",
    "EVENT_DATES" : "November 10, 2019",
    "EVENT_SPACE_NAME" : "Queen Hippie Gypsie",
    "EVENT_SPACE_ADDRESS" : "337 14th St, Oakland, CA 94612",
    "EVENT_ORGANIZER" : "Men of Substance",
    "EVENT_ORGANIZER_URL": "https://www.facebook.com/MenOfSubstanceMag/",
    "EVENT_EMAIL" : "menofsubstancemag@gmail.com",
    "EVENT_MODAL_ID" : "black_to_yoga",
  }, 
]

spaces = [
  {
    "content" : "spaces/kingston11.html",
    "output" : "docs/kingston11.html",
    "SPACE_LOGO" : "/static/images/spaces/k11_logo2.png",
    "SPACE_NAME" : "Kingston 11 Cuisine",
    "SPACE_IMAGE" : "/static/images/spaces/k11_event_space.jpg",
    "SPACE_PAGE_LINK" : "/spaces/kingston11.html",
  },
  {
    "content" : "spaces/queen_hippie_gypsy.html",
    "output" : "docs/queen_hippie_gypsy.html",
    "SPACE_LOGO" : "/static/images/spaces/qhg_storefront.jpg",
    "SPACE_NAME" : "Queen Hippie Gypsy",
    "SPACE_IMAGE" : "/static/images/spaces/qhg_kyrah_eventspace.jpg",
    "SPACE_PAGE_LINK" : "/spaces/queen_hippie_gypsy.html",
  },
  {
    "content" : "spaces/SAE_Expression_College.html",
    "output" : "docs/SAE_Expression_College.html",
    "SPACE_LOGO" : "/static/images/spaces/sae_logo.jpg",
    "SPACE_NAME" : "SAE Expression College",
    "SPACE_IMAGE" : "/static/images/spaces/sae_outdoor.jpg",
    "SPACE_PAGE_LINK" : "/spaces/SAE_Expression_College.html",
  }
]
